language: node_js
node_js:
 - "node"

 os:
  - linux
  - osx
  - windows

before_script: cd .. && git clone --depth=1 https://github.com/glarce/examples.git && cd Glarce
script: yarn testBuild

deploy:
  local-dir: ../examples/dev/dist
  skip-cleanup: true
  keep-history: true
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
