language: node_js
node_js:
 - "node"
before_script: git clone https://github.com/glarce/examples.git && cd examples && mv travis/ ../ && cd .. && cd travis && yarn && cd ..
script: yarn travis

deploy:
  local-dir: travis/dist
  skip-cleanup: true
  keep-history: true
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
